In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/MCOE/DS BDA/PARTB-DATASETS/dataset_Facebook.csv', sep=';')

In [3]:
df.head(5)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [4]:
#Create Subsets
subset = df[df["Page total likes"] > 100000 ]
subset

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433,100732,Photo,1,3,6,17,0.0,11420,23855,1411,1342,8049,16634,8032,865,12,211.0,14.0,237
434,100732,Photo,1,3,6,15,0.0,5704,10510,452,450,2895,9348,5388,361,1,15.0,1.0,17
435,100732,Photo,1,3,6,15,0.0,7192,12811,587,554,3941,11519,6616,472,11,95.0,4.0,110
436,100732,Photo,1,3,6,13,1.0,9604,16557,1061,1037,9614,13618,7984,705,16,127.0,0.0,143
437,100732,Photo,1,3,6,10,0.0,122944,457509,1373,1268,2106,72846,13184,475,0,136.0,13.0,149

In [5]:
subset2 = df[df['Lifetime Post Total Reach'] > 20000]
subset2

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,91009,Photo,1,2,1,12,0.0,21928,39641,1512,1479,1837,6338,3672,497,0,73.0,13.0,86
476,86909,Photo,1,1,6,10,1.0,37088,10966,2728,2288,3183,66311,34352,2021,7,579.0,47.0,633
477,86909,Link,1,1,6,4,0.0,39600,7927,572,496,581,12522,8176,167,1,101.0,5.0,107
482,86491,Photo,3,1,3,10,0.0,66784,9456,2969,2833,3645,17809,11328,801,3,187.0,36.0,226
492,85979,Link,1,1,5,11,0.0,45920,5808,753,655,763,15766,10720,220,0,128.0,9.0,137

In [6]:
#Merge data
merge_data = pd.merge(subset,subset2)
merge_data

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
1,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
2,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
3,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
4,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,107907,Photo,1,4,3,4,1.0,39568,47128,741,652,957,22022,16096,519,4,128.0,17.0,149
76,107907,Link,1,4,2,6,0.0,70912,94172,1374,1106,1267,42338,27232,788,1,379.0,40.0,420
77,106928,Link,1,4,6,4,0.0,34192,42092,338,322,389,22907,16464,230,1,36.0,7.0,44
78,104070,Photo,1,3,4,7,0.0,49632,1110282,1653,1480,2567,1107833,48368,1513,7,227.0,15.0,249
79,100732,Photo,1,3,6,10,0.0,122944,457509,1373,1268,2106,72846,13184,475,0,136.0,13.0,149

In [7]:
#Sort data
sort_data = df.sort_values("Lifetime Post Total Impressions", ascending = False)
sort_data

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
415,104070,Photo,1,3,4,7,0.0,49632,1110282,1653,1480,2567,1107833,48368,1513,7,227.0,15.0,249
460,92507,Photo,3,2,1,13,0.0,55520,665792,4544,3586,6624,648611,47488,3430,146,1546.0,181.0,1873
463,92186,Photo,3,2,7,2,1.0,153536,497910,1713,1633,2493,8907,5696,593,8,134.0,34.0,176
437,100732,Photo,1,3,6,10,0.0,122944,457509,1373,1268,2106,72846,13184,475,0,136.0,13.0,149
464,92079,Photo,1,2,6,13,0.0,158208,453213,2482,2319,3412,81938,20608,1034,9,268.0,36.0,313
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,136393,Photo,1,10,7,7,0.0,617,1071,229,223,265,935,521,191,1,3.0,2.0,6
120,136393,Photo,1,10,7,9,0.0,584,1029,273,271,308,943,511,232,0,2.0,NaN,2
426,100732,Photo,1,3,7,18,0.0,391,746,131,130,766,723,380,93,0,6.0,1.0,7
432,100732,Photo,1,3,6,17,0.0,452,726,186,184,889,721,450,114,0,4.0,1.0,5
422,102112,Photo,1,3,1,19,0.0,238,570,143,142,834,567,236,99,0,2.0,0.0,2

In [8]:
#Transpose data
transpose_data = df.T
transpose_data

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [9]:
#Shape 
df.shape

(500, 19)

In [20]:
frame1 = df.pivot_table(index = ['Type','Category'], columns = 'like', values = 'share')
frame1

like             0.0     1.0     2.0       3.0     4.0     5.0     6.0     \
Type   Category
Link   1            NaN     NaN     NaN       NaN     NaN     2.0     0.0
       2            NaN     NaN     NaN       NaN     NaN     NaN     NaN
       3            NaN     NaN     NaN       NaN     NaN     NaN     NaN
Photo  1            0.0     2.0     0.0  0.666667     1.0     NaN     1.5
       2            NaN     NaN     NaN       NaN     NaN     NaN     NaN
       3            NaN     NaN     NaN       NaN     NaN     NaN     NaN
Status 1            NaN     NaN     NaN       NaN     NaN     NaN     NaN
       2            NaN     NaN     NaN       NaN     NaN     NaN     NaN
       3            NaN     NaN     NaN       NaN     NaN     NaN     NaN
Video  1            NaN     NaN     NaN       NaN     NaN     NaN     NaN

like             7.0     8.0     9.0     ...  1047.0  1155.0  1372.0  1505.0  \
Type   Category                          ...
Link   1            NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
       2            NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
       3            NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
Photo  1            1.8     2.0     1.0  ...     NaN     NaN     NaN     NaN
       2            NaN     NaN     NaN  ...     NaN     NaN     NaN    95.0
       3            NaN     NaN     NaN  ...    98.0   102.0    47.0     NaN
Status 1            NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
       2            NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
       3            NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
Video  1            NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN

like             1546.0  1572.0  1622.0  1639.0  1998.0  5172.0
Type   Category
Link   1            NaN     NaN     NaN     NaN     NaN     NaN
       2            NaN     NaN     NaN     NaN     NaN     NaN
       3            NaN     NaN     NaN     NaN     NaN     NaN
Photo  1            NaN     NaN   208.0     NaN     NaN     NaN
       2            NaN   147.0     NaN     NaN     NaN   790.0
       3          181.0     NaN     NaN   122.0   128.0     NaN
Status 1            NaN     NaN     NaN     NaN     NaN     NaN
       2            NaN     NaN     NaN     NaN     NaN     NaN
       3            NaN     NaN     NaN     NaN     NaN     NaN
Video  1            NaN     NaN     NaN     NaN     NaN     NaN

[10 rows x 257 columns]

In [21]:
frame1.shape

(10, 257)